version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    groups:
      framework:
        patterns:
          - next
          - eslint-config-next
          - react
          - react-dom
          - "@types/react*"
        update-types:
          - minor
          - patch
      security:
        applies-to: security-updates
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - "*"
